'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsAuthors
    Inherits DataSet
    
    Private tableAuthorsAddress As AuthorsAddressDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("AuthorsAddress")) Is Nothing) Then
                Me.Tables.Add(New AuthorsAddressDataTable(ds.Tables("AuthorsAddress")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property AuthorsAddress As AuthorsAddressDataTable
        Get
            Return Me.tableAuthorsAddress
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsAuthors = CType(MyBase.Clone,dsAuthors)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("AuthorsAddress")) Is Nothing) Then
            Me.Tables.Add(New AuthorsAddressDataTable(ds.Tables("AuthorsAddress")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableAuthorsAddress = CType(Me.Tables("AuthorsAddress"),AuthorsAddressDataTable)
        If (Not (Me.tableAuthorsAddress) Is Nothing) Then
            Me.tableAuthorsAddress.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsAuthors"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dsAuthors.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableAuthorsAddress = New AuthorsAddressDataTable
        Me.Tables.Add(Me.tableAuthorsAddress)
    End Sub
    
    Private Function ShouldSerializeAuthorsAddress() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub AuthorsAddressRowChangeEventHandler(ByVal sender As Object, ByVal e As AuthorsAddressRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class AuthorsAddressDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnau_fname As DataColumn
        
        Private columnau_lname As DataColumn
        
        Private columnaddress As DataColumn
        
        Private columncity As DataColumn
        
        Private columnstate As DataColumn
        
        Private columnzip As DataColumn
        
        Friend Sub New()
            MyBase.New("AuthorsAddress")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property au_fnameColumn As DataColumn
            Get
                Return Me.columnau_fname
            End Get
        End Property
        
        Friend ReadOnly Property au_lnameColumn As DataColumn
            Get
                Return Me.columnau_lname
            End Get
        End Property
        
        Friend ReadOnly Property addressColumn As DataColumn
            Get
                Return Me.columnaddress
            End Get
        End Property
        
        Friend ReadOnly Property cityColumn As DataColumn
            Get
                Return Me.columncity
            End Get
        End Property
        
        Friend ReadOnly Property stateColumn As DataColumn
            Get
                Return Me.columnstate
            End Get
        End Property
        
        Friend ReadOnly Property zipColumn As DataColumn
            Get
                Return Me.columnzip
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As AuthorsAddressRow
            Get
                Return CType(Me.Rows(index),AuthorsAddressRow)
            End Get
        End Property
        
        Public Event AuthorsAddressRowChanged As AuthorsAddressRowChangeEventHandler
        
        Public Event AuthorsAddressRowChanging As AuthorsAddressRowChangeEventHandler
        
        Public Event AuthorsAddressRowDeleted As AuthorsAddressRowChangeEventHandler
        
        Public Event AuthorsAddressRowDeleting As AuthorsAddressRowChangeEventHandler
        
        Public Overloads Sub AddAuthorsAddressRow(ByVal row As AuthorsAddressRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddAuthorsAddressRow(ByVal au_fname As String, ByVal au_lname As String, ByVal address As String, ByVal city As String, ByVal state As String, ByVal zip As String) As AuthorsAddressRow
            Dim rowAuthorsAddressRow As AuthorsAddressRow = CType(Me.NewRow,AuthorsAddressRow)
            rowAuthorsAddressRow.ItemArray = New Object() {au_fname, au_lname, address, city, state, zip}
            Me.Rows.Add(rowAuthorsAddressRow)
            Return rowAuthorsAddressRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As AuthorsAddressDataTable = CType(MyBase.Clone,AuthorsAddressDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New AuthorsAddressDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnau_fname = Me.Columns("au_fname")
            Me.columnau_lname = Me.Columns("au_lname")
            Me.columnaddress = Me.Columns("address")
            Me.columncity = Me.Columns("city")
            Me.columnstate = Me.Columns("state")
            Me.columnzip = Me.Columns("zip")
        End Sub
        
        Private Sub InitClass()
            Me.columnau_fname = New DataColumn("au_fname", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnau_fname)
            Me.columnau_lname = New DataColumn("au_lname", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnau_lname)
            Me.columnaddress = New DataColumn("address", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnaddress)
            Me.columncity = New DataColumn("city", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columncity)
            Me.columnstate = New DataColumn("state", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnstate)
            Me.columnzip = New DataColumn("zip", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnzip)
            Me.columnau_fname.AllowDBNull = false
            Me.columnau_lname.AllowDBNull = false
        End Sub
        
        Public Function NewAuthorsAddressRow() As AuthorsAddressRow
            Return CType(Me.NewRow,AuthorsAddressRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New AuthorsAddressRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(AuthorsAddressRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.AuthorsAddressRowChangedEvent) Is Nothing) Then
                RaiseEvent AuthorsAddressRowChanged(Me, New AuthorsAddressRowChangeEvent(CType(e.Row,AuthorsAddressRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.AuthorsAddressRowChangingEvent) Is Nothing) Then
                RaiseEvent AuthorsAddressRowChanging(Me, New AuthorsAddressRowChangeEvent(CType(e.Row,AuthorsAddressRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.AuthorsAddressRowDeletedEvent) Is Nothing) Then
                RaiseEvent AuthorsAddressRowDeleted(Me, New AuthorsAddressRowChangeEvent(CType(e.Row,AuthorsAddressRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.AuthorsAddressRowDeletingEvent) Is Nothing) Then
                RaiseEvent AuthorsAddressRowDeleting(Me, New AuthorsAddressRowChangeEvent(CType(e.Row,AuthorsAddressRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveAuthorsAddressRow(ByVal row As AuthorsAddressRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class AuthorsAddressRow
        Inherits DataRow
        
        Private tableAuthorsAddress As AuthorsAddressDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableAuthorsAddress = CType(Me.Table,AuthorsAddressDataTable)
        End Sub
        
        Public Property au_fname As String
            Get
                Return CType(Me(Me.tableAuthorsAddress.au_fnameColumn),String)
            End Get
            Set
                Me(Me.tableAuthorsAddress.au_fnameColumn) = value
            End Set
        End Property
        
        Public Property au_lname As String
            Get
                Return CType(Me(Me.tableAuthorsAddress.au_lnameColumn),String)
            End Get
            Set
                Me(Me.tableAuthorsAddress.au_lnameColumn) = value
            End Set
        End Property
        
        Public Property address As String
            Get
                Try 
                    Return CType(Me(Me.tableAuthorsAddress.addressColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAuthorsAddress.addressColumn) = value
            End Set
        End Property
        
        Public Property city As String
            Get
                Try 
                    Return CType(Me(Me.tableAuthorsAddress.cityColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAuthorsAddress.cityColumn) = value
            End Set
        End Property
        
        Public Property state As String
            Get
                Try 
                    Return CType(Me(Me.tableAuthorsAddress.stateColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAuthorsAddress.stateColumn) = value
            End Set
        End Property
        
        Public Property zip As String
            Get
                Try 
                    Return CType(Me(Me.tableAuthorsAddress.zipColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAuthorsAddress.zipColumn) = value
            End Set
        End Property
        
        Public Function IsaddressNull() As Boolean
            Return Me.IsNull(Me.tableAuthorsAddress.addressColumn)
        End Function
        
        Public Sub SetaddressNull()
            Me(Me.tableAuthorsAddress.addressColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IscityNull() As Boolean
            Return Me.IsNull(Me.tableAuthorsAddress.cityColumn)
        End Function
        
        Public Sub SetcityNull()
            Me(Me.tableAuthorsAddress.cityColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsstateNull() As Boolean
            Return Me.IsNull(Me.tableAuthorsAddress.stateColumn)
        End Function
        
        Public Sub SetstateNull()
            Me(Me.tableAuthorsAddress.stateColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IszipNull() As Boolean
            Return Me.IsNull(Me.tableAuthorsAddress.zipColumn)
        End Function
        
        Public Sub SetzipNull()
            Me(Me.tableAuthorsAddress.zipColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class AuthorsAddressRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As AuthorsAddressRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As AuthorsAddressRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As AuthorsAddressRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
