'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsPhoneLookup
    Inherits DataSet
    
    Private tableAuthorPhone As AuthorPhoneDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("AuthorPhone")) Is Nothing) Then
                Me.Tables.Add(New AuthorPhoneDataTable(ds.Tables("AuthorPhone")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property AuthorPhone As AuthorPhoneDataTable
        Get
            Return Me.tableAuthorPhone
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsPhoneLookup = CType(MyBase.Clone,dsPhoneLookup)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("AuthorPhone")) Is Nothing) Then
            Me.Tables.Add(New AuthorPhoneDataTable(ds.Tables("AuthorPhone")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableAuthorPhone = CType(Me.Tables("AuthorPhone"),AuthorPhoneDataTable)
        If (Not (Me.tableAuthorPhone) Is Nothing) Then
            Me.tableAuthorPhone.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsPhoneLookup"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dsPhoneLookup.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableAuthorPhone = New AuthorPhoneDataTable
        Me.Tables.Add(Me.tableAuthorPhone)
    End Sub
    
    Private Function ShouldSerializeAuthorPhone() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub AuthorPhoneRowChangeEventHandler(ByVal sender As Object, ByVal e As AuthorPhoneRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class AuthorPhoneDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnphone As DataColumn
        
        Friend Sub New()
            MyBase.New("AuthorPhone")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property phoneColumn As DataColumn
            Get
                Return Me.columnphone
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As AuthorPhoneRow
            Get
                Return CType(Me.Rows(index),AuthorPhoneRow)
            End Get
        End Property
        
        Public Event AuthorPhoneRowChanged As AuthorPhoneRowChangeEventHandler
        
        Public Event AuthorPhoneRowChanging As AuthorPhoneRowChangeEventHandler
        
        Public Event AuthorPhoneRowDeleted As AuthorPhoneRowChangeEventHandler
        
        Public Event AuthorPhoneRowDeleting As AuthorPhoneRowChangeEventHandler
        
        Public Overloads Sub AddAuthorPhoneRow(ByVal row As AuthorPhoneRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddAuthorPhoneRow(ByVal phone As String) As AuthorPhoneRow
            Dim rowAuthorPhoneRow As AuthorPhoneRow = CType(Me.NewRow,AuthorPhoneRow)
            rowAuthorPhoneRow.ItemArray = New Object() {phone}
            Me.Rows.Add(rowAuthorPhoneRow)
            Return rowAuthorPhoneRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As AuthorPhoneDataTable = CType(MyBase.Clone,AuthorPhoneDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New AuthorPhoneDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnphone = Me.Columns("phone")
        End Sub
        
        Private Sub InitClass()
            Me.columnphone = New DataColumn("phone", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnphone)
            Me.columnphone.AllowDBNull = false
        End Sub
        
        Public Function NewAuthorPhoneRow() As AuthorPhoneRow
            Return CType(Me.NewRow,AuthorPhoneRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New AuthorPhoneRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(AuthorPhoneRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.AuthorPhoneRowChangedEvent) Is Nothing) Then
                RaiseEvent AuthorPhoneRowChanged(Me, New AuthorPhoneRowChangeEvent(CType(e.Row,AuthorPhoneRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.AuthorPhoneRowChangingEvent) Is Nothing) Then
                RaiseEvent AuthorPhoneRowChanging(Me, New AuthorPhoneRowChangeEvent(CType(e.Row,AuthorPhoneRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.AuthorPhoneRowDeletedEvent) Is Nothing) Then
                RaiseEvent AuthorPhoneRowDeleted(Me, New AuthorPhoneRowChangeEvent(CType(e.Row,AuthorPhoneRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.AuthorPhoneRowDeletingEvent) Is Nothing) Then
                RaiseEvent AuthorPhoneRowDeleting(Me, New AuthorPhoneRowChangeEvent(CType(e.Row,AuthorPhoneRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveAuthorPhoneRow(ByVal row As AuthorPhoneRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class AuthorPhoneRow
        Inherits DataRow
        
        Private tableAuthorPhone As AuthorPhoneDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableAuthorPhone = CType(Me.Table,AuthorPhoneDataTable)
        End Sub
        
        Public Property phone As String
            Get
                Return CType(Me(Me.tableAuthorPhone.phoneColumn),String)
            End Get
            Set
                Me(Me.tableAuthorPhone.phoneColumn) = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class AuthorPhoneRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As AuthorPhoneRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As AuthorPhoneRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As AuthorPhoneRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
